title = "My works as a illustrator"

[works]
[[works.illustrations]]
name = "å¤©å®®ã“ã“ã‚"
category = "Fanfiction"
genre = "Vtuber"
x_likes = 8822
x_reposts = 1361
x_user_id = "wakadori_Mk3"
x_post_date = "2021-09-08T11:27:00+09:00"
x_post_message = "3DãŠã‚ã§ã¨ã†ã”ã–ã„ã¾ã™ï¼"
x_post_url = "https://twitter.com/wakadori_Mk3/status/1435565444706963459"
x_post_hashtag = ["çµµã“ã“ã‚"]
image_urls = ["https://pbs.twimg.com/media/E-wmSP8UcBAYX9-?format=jpg&name=4096x4096"]

[[works.illustrations]]
name = "ç…ç™½ã¼ãŸã‚“"
category = "Fanfiction"
genre = "Vtuber"
x_likes = 4452
x_reposts = 566
x_user_id = "wakadori_Mk3"
x_post_date = "2021-10-25T12:44:00+09:00"
x_post_message = "æ–°è¡£è£…&100ä¸‡äººç™»éŒ²ãŠã‚ã§ã¨ã†ã”ã–ã„ã¾ã™ï¼"
x_post_url = "https://x.com/wakadori_Mk3/status/1452617086178529284"
x_post_hashtag = ["ã—ã—ã‚‰ãƒ¼ã¨"]
image_urls = ["https://pbs.twimg.com/media/FCi6IbpVgAUQUss?format=jpg&name=4096x4096"]

[[works.illustrations]]
name = "å¤©å®®ã“ã“ã‚"
category = "Fanfiction"
genre = "Vtuber"
x_likes = 4498
x_reposts = 503
x_user_id = "wakadori_Mk3"
x_post_date = "2021-10-25T14:54:00+09:00"
x_post_message = "ğŸ¾"
x_post_url = "https://x.com/wakadori_Mk3/status/1481278541056864259"
x_post_hashtag = ["çµµã“ã“ã‚"]
image_urls = ["https://pbs.twimg.com/media/FI6Nv84akAcB8gA?format=jpg&name=4096x4096"]

[[works.illustrations]]
name = "åšè¡£ã“ã‚ˆã‚Š"
category = "Fanfiction"
genre = "Vtuber"
x_likes = 5221
x_reposts = 814
x_user_id = "wakadori_Mk3"
x_post_date = "2022-01-03T14:48:00+09:00"
x_post_message = "æ–°è¡£è£…ãŠã‚ã§ã¨ã†ã”ã–ã„ã¾ã™ï¼"
x_post_url = "https://x.com/wakadori_Mk3/status/1478015533509640192"
x_post_hashtag = ["ã“ã‚ˆã‚Šã™ã‘ã£ã¡"]
image_urls = ["https://pbs.twimg.com/media/FIL3KXZacAIBv48?format=jpg&name=4096x4096"]

[[works.illustrations]]
name = "ç…ç™½ã¼ãŸã‚“"
category = "Fanfiction"
genre = "Vtuber"
x_likes = 2564
x_reposts = 381
x_user_id = "wakadori_Mk3"
x_post_date = "2022-05-02T12:00:00+09:00"
x_post_message = "ãµã‚Šãµã‚Šæ°´ç€ã—ã—ã‚ã‚“â™Œ"
x_post_url = "https://x.com/wakadori_Mk3/status/1521097173705781249"
x_post_hashtag = ["ã—ã—ã‚‰ãƒ¼ã¨", "ãƒ›ãƒ­ãƒ©ã‚¤ãƒ–ã‚µãƒãƒ¼ã«é¡˜ã„ã‚’"]
image_urls = ["https://pbs.twimg.com/media/FRwBiI5VUAEDnWh?format=jpg&name=4096x4096"]

[[works.illustrations]]
name = "ãƒ–ãƒ©ãƒƒã‚¯ãƒã‚¸ã‚·ãƒ£ãƒ³ã‚¬ãƒ¼ãƒ«"
category = "Fanfiction"
genre = "éŠæˆ¯ç‹"
x_likes = 2055
x_reposts = 501
x_user_id = "wakadori_Mk3"
x_post_date = "2022-03-08T11:05:00+09:00"
x_post_message = "è‰²è¤ªã›ãªã„ã‹ã‚ã„ã•"
x_post_url = "https://x.com/wakadori_Mk3/status/1501152242992181250"
x_post_hashtag = ["éŠæˆ¯ç‹", "ãƒã‚¹ã‚¿ãƒ¼ãƒ‡ãƒ¥ã‚¨ãƒ«", "BMG"]
image_urls = ["https://pbs.twimg.com/media/FNUqAbBVEAMe1QA?format=jpg&name=medium"]

[[works.illustrations]]
name = "ãƒ­ãƒœå­ã•ã‚“"
category = "Fanfiction"
genre = "Vtuber"
x_likes = 3319
x_reposts = 443
x_user_id = "wakadori_Mk3"
x_post_date = "2021-06-09T12:27:00+09:00"
x_post_message = "ãƒ­ãƒœå­ã•ã‚“æ–°è¡£è£…ãŠã‚ã§ã¨ã†ï¼"
x_post_url = "https://x.com/wakadori_Mk3/status/1402603313967767552"
x_post_hashtag = ["ãƒ­ãƒœå­Art", "ãƒ­ãƒœå­ã•ã‚“æ–°è¡£è£…"]
image_urls = ["https://pbs.twimg.com/media/E3cLsqZVgAEKjbt?format=jpg&name=4096x4096"]

[[works.illustrations]]
name = "å‘¨å¤®ã‚µãƒ³ã‚´"
category = "Fanfiction"
genre = "Vtuber"
x_likes = 1046
x_reposts = 222
x_user_id = "wakadori_Mk3"
x_post_date = "2021-06-19T13:09:00+09:00"
x_post_message = "ãƒ”ãƒ³ã‚¯ã®å°æ‚ªé­”ğŸ’ğŸ¦©"
x_post_url = "https://x.com/wakadori_Mk3/status/1406237750366326793"
x_post_hashtag = ["æããƒ³ã‚´", "å‘¨å¤®ã‚µãƒ³ã‚´"]
image_urls = ["https://pbs.twimg.com/media/E4P0nSpUYAcb-zo?format=jpg&name=4096x4096"]

[[works.illustrations]]
name = "Finana Ryugu"
category = "Fanfiction"
genre = "Vtuber"
x_likes = 894
x_reposts = 101
x_user_id = "wakadori_Mk3"
x_post_date = "2021-11-23T13:37:00+09:00"
x_post_message = "Congratulations on your six-month debut."
x_post_url = "https://x.com/wakadori_Mk3/status/1463139746746568709"
x_post_hashtag = ["Finanart"]
image_urls = ["https://pbs.twimg.com/media/FE4bnriakAYuIG2?format=jpg&name=4096x4096"]

[[works.illustrations]]
name = "åœ°é›·ã¡ã‚ƒã‚“"
category = "Original"
x_likes = 45
x_reposts = 12
x_user_id = "wakadori_Mk3"
x_post_date = "2023-01-12T04:33:00+09:00"
x_post_message = "åœ°é›·ã¡ã‚ƒã‚“"
x_post_url = "https://x.com/wakadori_Mk3/status/1613423893355823110"
x_post_hashtag = ["å‰µä½œ", "ã‚ªãƒªã‚¸ãƒŠãƒ«"]
image_urls = ["https://pbs.twimg.com/media/FmQICOvaYAAhciE?format=jpg&name=4096x4096"]